# Generated by Django 5.2.13 on 2026-04-23 10:04

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_officer', '0002_alter_collection_options_alter_service_options_and_more'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectschedule',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='collectschedule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='collectschedule',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
