# Generated by Django 5.2.13 on 2026-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_officer', '0002_alter_collection_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectschedule',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='collectschedule',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
